##################################################
### EndeavourOS workplace setup
- hosts: localhost
  become: yes

  ### Configuration
  vars:
    pacman_packages:
      - chromium
      - code
      - geary
      - git
      - keepass
      - lsof
      - nmap
      - nmon
      - pdfsam
      - tree
      - vim
#      - linux-headers # needed for virtualbox
#      - virtualbox
#      - virtualbox-host-dkms
#      - vagrant
    aur_packages:
      - acroread
      - seafile-client-git
      - shutter
      - signal-desktop
      - spotify
    snap_packages:
      - ""
    unneeded_packages:
      - ""
    install_docker: true

  ### Installation
  tasks:
    - name: "start | Debug"
      debug:
        msg: "Starting endeavouros-workplace-setup..."

    # Pacman
    - name: "pacman | Remove unneeded packages"
      pacman:
        name: "{{ unneeded_packages }}"
        state: absent

    - name: "pacman | Upgrade all installed packages"
      pacman:
        update_cache: yes
        upgrade: yes

    - name: "pacman | Install pacman packages"
      package:
        name: "{{ pacman_packages }}"
        state: latest
      when:
        - pacman_packages is defined
        - pacman_packages|length|int >=1
        - pacman_packages[0]|length|int >= 1

    # Arch user repo
    - name: "aur | Install arch user repo packages"
      become: no
      shell: "pacman -Q | grep {{ item }} || yay -S --noconfirm --norebuild {{ item }}"
      register: aur_install_state
      changed_when: "'install' in aur_install_state.stdout"
      with_items: "{{ aur_packages }}"
      when:
        - aur_packages is defined
        - aur_packages|length|int >=1
        - aur_packages[0]|length|int >= 1

    # Snap
    - name: "snap | Prepare snap and install packages"
      block:
        - name: "snap | Check if snap is installed already"
          become: no
          shell: "yay -Q snapd"
          register: snapd_installed
          changed_when: snapd_installed.rc|int == 1
          failed_when: false

        - name: "snap | Install snap via yay"
          become: no
          shell: "yay -S --noconfirm snapd"
          when: snapd_installed is changed

        - name: "snap | Start and enable snap systemd config"
          service:
            name: snapd
            state: started
            enabled: yes

        - name: "snap | Create softlink for /snap"
          file:
            src: "/var/lib/snapd/snap"
            dest: "/snap"
            state: link

        - name: "snap | Install snap packages"
          snap:
            name: "{{ snap_packages }}"
            state: present

      when:
        - snap_packages is defined
        - snap_packages|length|int >= 1
        - snap_packages[0]|length|int >= 1

    # Docker
    - name: "docker | Install and configure docker"
      block:
        - name: "docker | Configure kernel module loop"
          lineinfile:
            path: "/etc/modules-load.d/loop.conf"
            line: "loop"
            create: "yes"

        - name: "docker | Install docker packages"
          package:
            name:
              - docker
              - docker-compose
            state: latest

        - name: "docker | Start and enable docker systemd config"
          service:
            name: docker
            enabled: yes

        - name: "docker | Get username"
          become: no
          shell: "whoami"
          register: username
          changed_when: false

        - name: "docker | Add user to docker group"
          user:
            name: "{{ username.stdout }}"
            groups: docker
            append: true

      when:
        - install_docker is defined
        - install_docker

    # Further tasks
    - name: "inputrc | Configure page up and down for history search"
      lineinfile:
        path: "~/.inputrc"
        line: "{{ item }}"
        create: yes
      with_items:
        - '"\e[5~": history-search-backward'
        - '"\e[6~": history-search-forward'

    - name: "timesyncd | Start and enable systemd-timesyncd"
      systemd:
        name: "systemd-timesyncd"
        state: started
        enabled: yes

    # Final
    - name: "final | Debug"
      debug:
        msg: "Finished endeavouros-workplace-setup. Reboot your system to use all new tools."
